name: medicare-medicaid-analysis-viz-ml
channels:
  - defaults
dependencies:
  - python=3.12
  - pandas
  - statsmodels
  - scikit-learn
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - seaborn
  - plotly
  - nodejs
  - pyarrow